### ISSUE TITLE
Create concept images

### ISSUE THREAD

**Issue by heyimocto** [clover-os/CloverOS#1]

**Comment by CloverTheBunny** [comment]
I made 2 concept images for the texting. The color scheme should be more green but I just decided to use the colors that looked good at the moment: 



![Image](https://user-images.githubusercontent.com/85404762/208760976-97c34809-eee9-42b3-93e3-4529ab20ac3c.svg)
![Image](https://user-images.githubusercontent.com/85404762/208760978-420ef026-7f55-4c6d-9035-acf2617195c5.svg)

**Comment by heyimocto** [comment]
Okay, that looks good! Do you think we should be taking inspiration from something like macOS or Windows, or make our own unique design?

**Comment by heyimocto** [comment]
![Image](https://user-images.githubusercontent.com/72633854/208781314-7fc5c9d2-2797-4347-b0d9-bf0ac917bd3b.png)

concept v1

**Comment by CloverTheBunny** [comment]
cool!

**Comment by heyimocto** [comment]
thanks! im using the font "TT Interphases" btw

**Comment by heyimocto** [comment]
hey @CloverTheBunny, can you work on more concepts? (web browser, boot up, login, etc.)

**Comment by CloverTheBunny** [comment]
> Okay, that looks good! Do you think we should be taking inspiration from something like macOS or Windows, or make our own unique design?

Unique, but still modern/smooth.

**Comment by CloverTheBunny** [comment]
> hey @CloverTheBunny, can you work on more concepts? (web browser, boot up, login, etc.)

k

**Comment by heyimocto** [comment]
> > Okay, that looks good! Do you think we should be taking inspiration from something like macOS or Windows, or make our own unique design?
> 
> Unique, but still modern/smooth.

Okay, so is the desktop design I made good, or do changes need to be made?

**Comment by CloverTheBunny** [comment]
> > > Okay, that looks good! Do you think we should be taking inspiration from something like macOS or Windows, or make our own unique design?
> > 
> > 
> > Unique, but still modern/smooth.
> 
> Okay, so is the desktop design I made good, or do changes need to be made?

its good!

**Comment by heyimocto** [comment]
thanks!

**Comment by heyimocto** [comment]
**the first concept for ctalk!**
![image](https://user-images.githubusercontent.com/72633854/208791327-35220bd4-d719-4f5a-972c-1bf9a46f462f.png)

**Comment by CloverTheBunny** [comment]
![Group 1](https://user-images.githubusercontent.com/85404762/208796892-50b4c3cd-11e5-414c-ac38-9c295a82171c.png)

**Comment by heyimocto** [comment]
(made by @heyimocto and @CloverTheBunny)

**Comment by CloverTheBunny** [comment]
> (made by @heyimocto and @CloverTheBunny)

dinner soon so if I leave suddenly its bc of dinner

**Comment by heyimocto** [comment]
We now have all concept images!
